name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy on Ubuntu 18.04
    runs-on: ubuntu-latest
    steps:
    - name: Install main dependencies
      run: sudo apt-get install cmake