name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy on Ubuntu 18.04
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install main dependencies
      run: ./scripts/install.sh    

    - name: Install third-party dependencies
      run: ./scripts/install-third-party.sh

    - name: Build library
      run: ./scripts/build.sh      