name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy on Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install valgrind
      run: sudo apt-get install valgrind    

    # - name: Install main dependencies
    #   run: ./scripts/install.sh    

    # - name: Install third-party dependencies
    #   run: ./scripts/install-third-party.sh

    # - name: Build
    #   run: ./scripts/build.sh

    # - name: Tests
    #   run: ./scripts/test.sh

    # - name: Static analysis
    #   run: ./scripts/sanalyze.sh

    # - name: Code style
    #   run: ./scripts/codestyle.sh

    # - name: Documentation
    #   run: ./scripts/doc.sh

    # - name: Dynamic analysis
    #   run: ./scripts/danalyze.sh

    # - name: Clang Tidy version
    #   run: clang-tidy --version