on:
	push:
		branches:
			- '*'

jobs:
	run_tests:
		runs-on: [ubuntu-latest]

steps:
	- name: Install main requirements
		run: ./scripts/install.sh
	- name: Install third-party requirements
		run: ./scripts/install-third-party.sh
	- name: Run tests
		run: ./scripts/test.sh


